sudo: required
os: linux
language: javascript
services:
    - docker

before_install:
    - docker build -t gerrading/docker-react -f Dockerfile.dev .


script:
    - docker run -e CI=true gerrading/docker-react npm run test